### ISSUE TITLE
pywin xc32w error

### ISSUE THREAD

**Issue by KDot227** [qPhantasm/Reaper-Nuker#1]

**Comment by KDot227** [comment]
I can prolly guess why ngl

**Comment by KDot227** [comment]
Also the bot nuker is terrible 💀 why is it looping inside the loops

**Comment by qPhantasm** [comment]
> I can prolly guess why ngl

pssstt 🤫

**Comment by qPhantasm** [comment]
> Also the bot nuker is terrible 💀 why is it looping inside the loops
A friend made it and said I could use it yea if I got time I'll add more and fix some stuff

**Comment by qPhantasm** [comment]
Why isn't your main.exe from your Batch-Grabber open source 😬

**Comment by KDot227** [comment]
> Why isn't your main.exe from your Batch-Grabber open source 😬

It is I have the src in the py file... Nt tho

**Comment by KDot227** [comment]
and wdym cd cmd win error 💀 u could have atleast made it believeable

**Comment by qPhantasm** [comment]
> > Why isn't your main.exe from your Batch-Grabber open source 😬
> 
> It is I have the src in the py file... Nt tho

oh lmao

**Comment by qPhantasm** [comment]
> and wdym cd cmd win error 💀 u could have atleast made it believeable

bro it is believable a few days ago some weird dude got a weird cd error in cmd

**Comment by qPhantasm** [comment]
> Also the bot nuker is terrible 💀 why is it looping inside the loops

don't you wanna try the program on your pc? just run the batch file (dw, it's safe) xD

**Comment by KDot227** [comment]
> > Also the bot nuker is terrible 💀 why is it looping inside the loops
> 
> don't you wanna try the program on your pc? just run the batch file (dw, it's safe) xD

ill just debug it when im home and pull out your webhook

**Comment by qPhantasm** [comment]
> > > Also the bot nuker is terrible 💀 why is it looping inside the loops
> > 
> > don't you wanna try the program on your pc? just run the batch file (dw, it's safe) xD
> 
> ill just debug it when im home and pull out your webhook

okay ima delete all your comments and put a new one in, it's not that hard, btw it was a joke, too dumb to get it?

**Comment by KDot227** [comment]
Imagine deleting my comments 🤡🤡🤡
